spring.application.name=Oauth2Understanding

spring.security.oauth2.client.registration.google.client-id=

spring.security.oauth2.client.registration.google.client-secret=

spring.security.oauth2.client.registration.google.scope=openid,profile,email

#193593533943-ept8d3es9td9qoilr3lqctv87h51r2o4.apps.googleusercontent.comGOCSPX-21_8cRgur7hBvq2yykaTx_YMHRmj
